name: AddAsyncApiPublishMessage
spryk: wrapper
description: "Adds code to be able to receive a defined message. You can publish me this message."
mode: both
level: 2
application: Zed

priority: 1

arguments:
    module:
        description: "The module name to which the message belongs to."
        inherit: true

    organization:
        inherit: true
        value: Spryker

    application:
        inherit: true
        value: Zed

    messageName: ~
    channelName: ~
    messages:
        description: "Pass multiple properties in one by using --messages MessageA&propertyA:string,propertyB:int;MessageB&propertyA:string,propertyB:int"

    suite:
        value: "AsyncApi"

postSpryks:
    - AddComposerJson
    - UpdateJson:
          arguments:
              target:
                  value: "require"
              key:
                  value: "spryker/message-broker"
              value:
                  value: "^1.8.0"
              targetFilename:
                  value: composer.json
    - UpdateJson:
          arguments:
              target:
                  value: "require"
              key:
                  value: "spryker/testify-async-api"
              value:
                  value: "^0.1.0"
              targetFilename:
                  value: composer.json

    # Since we exclude the AddSharedTransferSchema which would also ensure the schema file exists
    # we need to add this one manually.
    - AddSharedTransferSchema
    # Add Message Transfer properties
    # This one will create many messages with properties
    - AddSharedTransferProperty:
          excludedSpryks:
              - AddSharedTransferSchema
          arguments:
              transfersProperties:
                  value: "{{ messages }}"

    # Add default required MessageAttributes Transfer
    - AddSharedTransferDefinition:
          arguments:
              name:
                  value: "MessageAttributes"

    # MessageHandlerPlugin
    - AddMessageBrokerMessageHandlerPlugin

    # Test
    ## tests/PyzTest/AsyncApi/Module/_support
    ## tests/PyzTest/AsyncApi/Module/_support/_generated
    ## tests/PyzTest/AsyncApi/Module/_support/ModuleAsyncApiTester.php
    ## tests/PyzTest/AsyncApi/Module/ModuleTests
    ## tests/PyzTest/AsyncApi/Module/ModuleTests/ChannelName
    ## tests/PyzTest/AsyncApi/Module/ModuleTests/ChannelName/MessageNameTest.php

    - AddSuiteConfiguration: # tests/PyzTest/AsyncApi/Module/codeception.yml
          arguments:
              application:
                  value: "AsyncApi"
              template:
                  value: Zed/AsyncApi/Tests/AsyncApiSuiteCodeceptionConfiguration.yml.twig

    - AddClass:
          arguments:
              channelName:
                  inherit: true
              messageName:
                  inherit: true
              application:
                  value: AsyncApi
              className:
                 value: "{{ messageName }}"
              isTestClass:
                  value: true
              template:
                  value: Zed/AsyncApi/Tests/AsyncApiMessageHandlingTestClass.yml.twig
              subDirectory:
                  value: "{{ module }}Tests/{{ channelName }}/"

    - AddTestHelperMethod:
          arguments:
              target:
                  value: "\\{{ organization }}Test\\AsyncApi\\{{ module }}\\Helper\\{{ module }}Helper"
              application:
                  value: AsyncApi
              method:
                  value: "have{{ messageName }}Transfer"
              input:
                  value: "array $seed = null"
              output:
                  value: "\\Generated\\Shared\\Transfer\\{{ messageName }}Transfer"
              body:
                  value:
                      - "return (new \\Generated\\Shared\\DataBuilder\\{{ messageName }}Builder($seed))->build();"
