name: AddGlueApiApplicationFactory
spryk: template
description: "Adds a new *module*Factory to the Glue application."
mode: both
level: 3
condition: "application === 'Glue'"

arguments:
    module:
        inherit: true
        default: "{{ resource | resourceNameToModuleName }}"
        callback: GlueResourceModuleName

    organization:
        inherit: true
        default: Spryker

    application:
        value: Glue

    applicationType:
        inherit: true
        description: "Can be one of: Backend or Storefront"
        default: Backend

    extends:
        callback: ResolveExtends
        value:
            - "\\Spryker\\{{ application }}\\{{ module }}\\{{ module }}Factory"
            - "\\Spryker\\{{ application }}\\Kernel{% if applicationType == 'Backend' %}\\Backend{% endif %}\\AbstractFactory"

    className:
        value: "{{ module }}Factory"

    template:
        value: Common/Class.php.twig

    targetFilename:
        value: "{{ module }}Factory.php"

    targetPath:
        value: "src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
    - AddGlueApiApplicationModule

postSpryks:
    - AddGlueApiApplicationDependencyProvider
    - AddModuleConfig:
          arguments:
              application:
                  value: Glue
