spryk: dependencyProvider
description: "Adds a Client dependency method to Container in *module*DependencyProvider."
mode: both
deprecated: Use AddDependencyBridgeMethod instead.

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    dependentModule:
        inherit: true

    provideMethod:
        value: "provideDependencies"

    providerMethod:
        inherit: true
        value: "add{{ dependentModule }}Client"

    template:
        value: Glue/Dependency/Client/GlueDependencyClientToDependencyProvider.php.twig

    target:
        value: "{{ organization }}\\Glue\\{{ module }}\\{{ module }}DependencyProvider"

preSpryks:
    - AddGlueDependencyClientDependencyProviderMethod
