name: AddZedBusinessMessageBrokerMessageHandlerMethod
spryk: method
description: "Adds a new message handler class to the **module** with the handle**messageName** method. This class::method will be called from the facade and should handle the message."
mode: both
level: 2

application: Zed
layer: Business

priority: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        inherit: true
        default: Zed

    className:
        value: "{{ messageName }}MessageHandler"

    subDirectory:
        value: "MessageBroker"

    messageName: ~

    modelMethod:
        value: "handle{{ messageName }}"

    input:
        value: "\\Generated\\Shared\\Transfer\\{{ messageName }}Transfer ${{ messageName | lcfirst }}Transfer"

    output:
        value: "void"

    body:
        value:
            - "// Handle the message here"

    facadeMethod:
        value: "{{ modelMethod }}"

    template:
        value: Common/Method.php.twig

    target:
        value: "{{ className }}"

    fqcnPattern:
        value: "{{ organization }}\\Zed\\{{ module }}\\Business\\MessageBroker\\{{ className }}"

preSpryks:
    - AddZedBusinessMessageBrokerMessageHandler
    - AddZedBusinessModelInterfaceMethod
