spryk: template
description: 'Adds a new MessageBroker MessageHandler to the Zed application.'
mode: both
level: 2
application: Zed
layer: Business
priority: 1
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    messageName:
        inherit: true
    className:
        value: '{{ module }}MessageHandler'
    subDirectory:
        inherit: true
        value: MessageBroker
    interfaceName:
        value: '\{{ organization}}\Zed\{{ module}}\Business\MessageBroker\{{ className }}Interface'
    template:
        value: Zed/Business/MessageBroker/MessageHandler.php.twig
    targetFilename:
        callbackOnly: true
        callback: ZedBusinessModelTargetFilenameCallback
    targetPath:
        value: 'src/{{ organization }}/Zed/{{ module }}/Business'
preSpryks:
    - AddModule
postSpryks:
    - AddZedBusinessModelInterface
    -
        AddZedBusinessFactoryMethod:
            arguments:
                subDirectory: MessageBroker
                dependencyMethods:
                    - getMessageBrokerFacade
    -
        AddZedBusinessFactoryDependencyMethod:
            arguments:
                dependencyType: Facade
                dependentModule: MessageBroker
                dependencyMethod: getMessageBrokerFacade
    -
        AddZedDependencyFacadeDependencyProviderMethod:
            arguments:
                dependentModule: MessageBroker
