name: AddZedBusinessMessageBrokerMessageHandler
# Adds a MessageHandler class
# Adds a MessageHandler interface
# Adds the Factory method to create the MessageHandler
# Adds a facade method to call the created handler
spryk: template
description: "Adds a new MessageBroker MessageHandler to the Zed application."
mode: both
level: 2

application: Zed
layer: Business

priority: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true

    application:
        inherit: true

    messageName:
        inherit: true

    className:
        value: "{{ messageName }}MessageHandler"

    subDirectory:
        inherit: true
        value: "Business/MessageBroker"

    interfaceName:
        value: "\\{{ organization}}\\Zed\\{{ module}}\\Business\\MessageBroker\\{{ className }}Interface"

    template:
        value: Common/Class.php.twig

    targetFilename:
        callbackOnly: true
        callback: ZedBusinessModelTargetFilenameCallback

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedBusinessModelInterface # Add Interface for the newly created method
