name: AddGlueApiApplicationResponseMapper
spryk: template
description: "Adds a new Response ResponseMapper that maps {{ zedDomainEntity }} transfers to a GlueResponseTransfer."
mode: both
level: 2

arguments:
    module: # Based on the applicationType the module name will be suffixed with BackendApi or StorefrontApi by the ResourceModuleName callback.
        inherit: true
        default: "{{ resource | resourceNameToModuleName }}{{ applicationType }}Api"

    organization:
        inherit: true
        default: Spryker

    className:
        value: "GlueResponse{{ resourceDataObject }}Mapper"

    resource:
        description: "Defines the resource name this resource plugin will work with."

    subDirectory:
        inherit: true
        value: Mapper

    application:
        inherit: true
        value: Glue

    applicationType:
        inherit: true
        description: "Can be one of: Backend or Storefront"
        default: "Backend"

    isTestClass:
        inherit: true
        isOptional: true
        default: false

    resourceDataObject:
        description: "Defines the Transfer that will be used in the Methods. Do not use Transfer as suffix, it will be added automatically. Example: Customer (ok) CustomerTransfer (wrong)"
        isOptional: true # Is not needed for all methods
        value: "{{ resource | resourceNameToModelName | singularize }}"

    template:
        value: Common/Class.php.twig

    zedDomainEntity:
        inherit: true
        description: "Defines the domainEntity used on Zed side for the CRUD Facade. It will be used to create all needed Transfer Objects."
        default: "{{ resource | resourceNameToModelName | singularize }}"

    implements:
        value: "\\{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueResponse{{ resourceDataObject }}MapperInterface"

    target:
        value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueResponse{{ resourceDataObject }}Mapper"

    targetFilename:
        value: "{{ className }}.php"

    targetPath:
        value: "src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
    - AddGlueApiApplicationController

postSpryks:
    - AddMethod:
          arguments:
              method:
                  value: "map{{ zedDomainEntity }}CollectionTransferToGlueResponseTransfer"
              input:
                  value: "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}CollectionTransfer ${{ zedDomainEntity | lcfirst }}CollectionTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\GlueResponseTransfer"
              body:
                  value: Glue/ApiApplication/ResponseMapper/MapCollectionTransferToGlueResponseTransfer.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueResponse{{ resourceDataObject }}Mapper"
              # Overloading AddMethod Spryk
              zedDomainEntity:
                  inherit: true
    - AddMethod:
          arguments:
              method:
                  value: "map{{ zedDomainEntity }}CollectionTransferToSingleResourceGlueResponseTransfer"
              input:
                  value: "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}CollectionTransfer ${{ zedDomainEntity | lcfirst }}CollectionTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\GlueResponseTransfer"
              body:
                  value: Glue/ApiApplication/ResponseMapper/MapCollectionTransferToSingleResourceGlueResponseTransfer.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueResponse{{ resourceDataObject }}Mapper"
              # Overloading AddMethod Spryk
              zedDomainEntity:
                  inherit: true
    - AddMethod:
          arguments:
              method:
                  value: "map{{ zedDomainEntity }}CollectionResponseTransferToGlueResponseTransfer"
              input:
                  value: "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}CollectionResponseTransfer ${{ zedDomainEntity | lcfirst }}CollectionResponseTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\GlueResponseTransfer"
              body:
                  value: Glue/ApiApplication/ResponseMapper/MapCollectionResponseTransferToGlueResponseTransfer.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueResponse{{ resourceDataObject }}Mapper"
              # Overloading AddMethod Spryk
              zedDomainEntity:
                  inherit: true
    - AddMethod:
          arguments:
              method:
                  value: "map{{ zedDomainEntity }}CollectionResponseTransferToSingleResourceGlueResponseTransfer"
              input:
                  value: "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}CollectionResponseTransfer ${{ zedDomainEntity | lcfirst }}CollectionResponseTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\GlueResponseTransfer"
              body:
                  value: Glue/ApiApplication/ResponseMapper/MapCollectionResponseTransferToSingleResourceGlueResponseTransfer.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueResponse{{ resourceDataObject }}Mapper"
              # Overloading AddMethod Spryk
              zedDomainEntity:
                  inherit: true
    - AddMethod:
          arguments:
              method:
                  value: "addNotFoundError"
              visbility:
                  value: protected
              input:
                  value: "\\Generated\\Shared\\Transfer\\GlueResponseTransfer $glueResponseTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\GlueResponseTransfer"
              body:
                  value: Glue/ApiApplication/ResponseMapper/AddNotFoundError.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueResponse{{ resourceDataObject }}Mapper"
              # Overloading AddMethod Spryk
              zedDomainEntity:
                  inherit: true
              withInterface:
                  value: false
    - AddMethod:
          arguments:
              method:
                  value: "add{{ zedDomainEntity }}TransferToGlueResponse"
              visbility:
                  value: protected
              input:
                  value:
                      - "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}Transfer ${{ zedDomainEntity | lcfirst }}Transfer"
                      - "\\Generated\\Shared\\Transfer\\GlueResponseTransfer $glueResponseTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\GlueResponseTransfer"
              body:
                  value: Glue/ApiApplication/ResponseMapper/AddResourceToGlueResponse.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueResponse{{ resourceDataObject }}Mapper"
              # Overloading AddMethod Spryk
              zedDomainEntity:
                  inherit: true
              withInterface:
                  value: false
    # Add factory method
    - AddGlueFactoryMethod:
          arguments:
              subDirectory:
                  value: "Mapper"
              className:
                  value: "GlueResponse{{ resourceDataObject }}Mapper"
