spryk: method
description: 'Adds a *domainEntity* method to the *module*PersistenceFactory.'
mode: both
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    subDirectory:
        inherit: true
        isOptional: true
    domainEntity:
        inherit: true
    className:
        isOptional: true
    fqcnClassName:
        isOptional: true
    interfaceName:
        inherit: true
        isOptional: true
    factoryMethod: ~
    dependencyMethods:
        isMultiple: true
        isOptional: true
    template:
        value: Zed/Persistence/PersistenceFactoryMethod.php.twig
    target:
        value: '{{ organization }}\Zed\{{ module }}\Persistence\{{ module }}PersistenceFactory'
preSpryks:
    - AddZedPersistenceFactory
