spryk: dependencyProvider
description: 'Adds a add dependency method to the Container in the *module*DependencyProvider::{{ providerMethod }}.'
mode: both
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    layer: ~
    provideMethod: ~
    providerMethod: ~
    template:
        value: Zed/Dependency/Common/ZedDependencyDependencyProviderContainerAddMethod.php.twig
    target:
        value: '{{ organization }}\Zed\{{ module }}\{{ module }}DependencyProvider'
preSpryks:
    - AddZedDependencyProvider
    - AddZedDependencyProviderProvideMethod
