spryk: structure
description: 'Adds a new POST Resource to the Glue application.'
mode: both
application: Glue
priority: 1
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    resourceType:
        inherit: true
        default: '{{ module | removeRestApiSuffix | lower }}'
    clientModule:
        inherit: true
    clientMethod:
        inherit: true
    resourceRouteMethod:
        value: post
    targetPath:
        default: 'src/{{ organization }}/Glue/{{ module }}/'
    directories:
        skipOnProjectLevel: true
        value:
            - ''
preSpryks:
    - AddModule
postSpryks:
    -
        AddGlueResourceRoute:
            arguments:
                modelSuffix: Creator
    -
        AddGlueDependencyClientBridgeMethod:
            arguments:
                dependentModule: '{{ clientModule }}'
                methods:
                    - '{{ clientMethod }}'
    -
        AddGlueFactoryMethod:
            arguments:
                className: '{{ resourceType | dashToCamelCase | singularize }}Creator'
                subDirectory: '{{ resourceType | dashToCamelCase | singularize }}'
                dependencyMethods:
                    - 'get{{ clientModule }}Client'
    -
        AddGlueProcessorModel:
            arguments:
                className: '{{ resourceType | dashToCamelCase | singularize }}Creator'
                subDirectory: '{{ resourceType | dashToCamelCase | singularize }}'
                constructorArguments:
                    - '\{{ organization }}\Glue\{{ module }}\Dependency\Client\{{ module }}To{{ clientModule }}ClientInterface ${{ clientModule | lcfirst }}Client'
    -
        AddGlueControllerPostAction:
            arguments:
                controllerMethod:
                    value: '{{ resourceRouteMethod }}'
                    callback: EnsureActionSuffixCallback
                controller:
                    value: '{{ resourceType | dashToCamelCase }}'
                    callback: EnsureResourceSuffix
                target:
                    value: '{{ organization }}\Glue\{{ module }}\Controller\{{ resourceType | dashToCamelCase }}'
                    callback:
                        - EnsureResourceSuffix
                        - EnsureControllerSuffixCallback
