spryk: template
description: 'Adds a new *module*DependencyProvider to the Glue application.'
mode: both
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    application:
        value: Glue
    extends:
        callback: ResolveExtends
        value:
            - '\Spryker\{{ application }}\{{ module }}\{{ module }}DependencyProvider'
            - '\Spryker\{{ application }}\Kernel\AbstractBundleDependencyProvider'
    className:
        value: '{{ module }}DependencyProvider'
    template:
        value: Common/Class.php.twig
    targetFilename:
        value: '{{ module }}DependencyProvider.php'
    targetPath:
        value: 'src/{{ organization }}/Glue/{{ module }}/'
preSpryks:
    - AddModule
postSpryks:
    -
        AddMethod:
            arguments:
                target: '\{{ organization }}\Glue\{{ module }}\{{ module }}DependencyProvider'
                withInterface: false
                input: '\Spryker\{{ application }}\Kernel\Container $container'
                output: '\Spryker\{{ application }}\Kernel\Container'
                method: provideDependencies
                body:
                    - '$container = parent::provideDependencies($container);'
                    - ''
                    - 'return $container;'
