name: AddGlueCommonDependencyProvider
spryk: template
description: "Adds a new *module*DependencyProvider to the Glue application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        value: Glue

    extends:
        callback: ResolveExtends
        value:
            - "\\Spryker\\{{ application }}\\{{ module }}\\{{ module }}DependencyProvider"
            - "\\Spryker\\{{ application }}\\Kernel\\AbstractBundleDependencyProvider"

    className:
        value: "{{ module }}DependencyProvider"

    template:
        value: Common/Class.php.twig

    targetFilename:
        value: "{{ module }}DependencyProvider.php"

    targetPath:
        value: "src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
    - AddModule

postSpryks:
    - AddMethod:
          arguments:
              target:
                  value: "\\{{ organization }}\\Glue\\{{ module }}\\{{ module }}DependencyProvider"
              withInterface:
                  value: false
              input:
                  value: "\\Spryker\\{{ application }}\\Kernel\\Container $container"
              output:
                  value: "\\Spryker\\{{ application }}\\Kernel\\Container"
              method:
                  value: "provideDependencies"
              body:
                  value:
                      - "$container = parent::provideDependencies($container);"
                      - ""
                      - "return $container;"
