spryk: template
description: 'Adds a new Communication model to the Zed application.'
mode: both
level: 2
application: Zed
layer: Communication
priority: 1
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    subDirectory:
        inherit: true
        isOptional: true
    className:
        inherit: true
    constructorArguments:
        type: ZedCommunicationDependency
        typeOptions:
            - module
            - spryk
        isOptional: true
        isMultiple: true
    interfaceName:
        value: '{{ className }}Interface'
    template:
        value: Zed/Communication/Model/ZedCommunicationModel.php.twig
    targetFilename:
        callbackOnly: true
        callback: ZedCommunicationModelTargetFilenameCallback
    targetPath:
        value: 'src/{{ organization }}/Zed/{{ module }}/Communication/'
preSpryks:
    - AddModule
postSpryks:
    - AddZedCommunicationModelInterface
    - AddZedCommunicationFactoryMethod
