spryk: template
description: 'Adds a new Communication model interface to the Zed application.'
mode: both
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    subDirectory:
        inherit: true
        isOptional: true
    className:
        inherit: true
    interfaceName:
        inherit: true
        value: '{{ className }}Interface'
    template:
        value: Zed/Communication/Model/ZedCommunicationModelInterface.php.twig
    targetFilename:
        callbackOnly: true
        callback: ZedCommunicationModelInterfaceTargetFilenameCallback
    targetPath:
        value: 'src/{{ organization }}/Zed/{{ module }}/Communication/'
preSpryks:
    - AddModule
