spryk: method
description: "Adds a new {{ zedDomainEntity }} aware method to the target class."
mode: both
level: 3

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true

    zedDomainEntity:
        inherit: true

    method: ~

    body:
        default: ""

    visibility:
        inherit: true
        default: public

    input:
        isOptional: true

    output:
        default: void

    template:
        value: Common/Method.php.twig

    target: ~

postSpryks:
    - AddInterfaceMethod
