spryk: method
description: 'Adds a facade dependency method to the *module*DependencyProvider.'
mode: both
deprecated: 'Use AddDependencyBridgeMethod instead.'
arguments:
    module:
        inherit: true
        moduleFilter:
            application: Zed
    dependentModule:
        inherit: true
        moduleFilter:
            application: Zed
    organization:
        inherit: true
        default: Spryker
    providerMethod:
        value: 'add{{ dependentModule }}Facade'
    template:
        value: Zed/Dependency/Facade/ZedDependencyFacadeDependencyProviderMethod.php.twig
    target:
        value: '{{ organization }}\Zed\{{ module }}\{{ module }}DependencyProvider'
preSpryks:
    - AddZedDependencyProvider
    -
        AddZedDependencyProviderProvideMethod:
            arguments:
                layer: Business
postSpryks:
    -
        AddZedDependencyFacadeToDependencyProvider:
            arguments:
                provideMethod: provideBusinessLayerDependencies
    -
        AddZedDependencyFacadeDependencyProviderConstant:
            arguments:
                name: 'FACADE_{{ dependentModule | camelCaseToUnderscore | upper }}'
                value: 'FACADE_{{ dependentModule | camelCaseToUnderscore | upper }}'
                visibility: public
