spryk: template
description: "Adds a new *module*To*dependentModule*FacadeInterface."
mode: both
deprecated: Use AddDependencyBridgeMethod instead.

arguments:
    module:
        inherit: true
        moduleFilter:
            application: Zed

    dependentModule:
        inherit: true
        moduleFilter:
            application: Zed

    organization:
        inherit: true
        default: Spryker

    template:
        value: Zed/Dependency/Facade/ZedDependencyFacadeInterface.php.twig

    targetFilename:
        value: "{{ module }}To{{ dependentModule }}FacadeInterface.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Dependency/Facade/"

preSpryks:
    - AddModule
