spryk: template
description: "Adds a new *Module*ServiceFactory to the Service application."
mode: both
level: 3
condition: "application === 'Service'"

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        value: "Service"

    template:
        value: Service/ServiceFactory.php.twig

    targetFilename:
        value: "{{ module }}Factory.php"

    targetPath:
        value: "src/{{ organization }}/Service/{{ module }}/"

preSpryks:
    - AddModule

