spryk: template
description: "Adds a new *Module*ServiceFactory to the Service application."
mode: both
level: 3
condition: "application === 'Service'"

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        inherit: true
        default: "Service"

    extends:
        callback: ResolveExtends
        value:
            - "\\Spryker\\{{ application }}\\{{ module }}\\{{ module }}Factory"
            - "\\Spryker\\{{ application }}\\Kernel\\AbstractServiceFactory"

    className:
        value: "{{ module }}Factory"

    template:
        value: Common/Class.php.twig

    targetFilename:
        value: "{{ module }}Factory.php"

    targetPath:
        value: "src/{{ organization }}/Service/{{ module }}/"

preSpryks:
    - AddModule

