spryk: template
description: "Adds a new *Module*ServiceDependencyProvider to the Service application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        value: Service

    extends:
        callback: ResolveExtends
        value:
            - "\\Spryker\\{{ application }}\\{{ module }}\\{{ module }}DependencyProvider"
            - "\\Spryker\\{{ application }}\\Kernel\\AbstractBundleDependencyProvider"

    className:
        value: "{{ module }}DependencyProvider"

    template:
        value: Common/Class.php.twig

    targetFilename:
        value: "{{ module }}DependencyProvider.php"

    targetPath:
        value: "src/{{ organization }}/Service/{{ module }}/"

preSpryks:
    - AddModule
