spryk: method
description: 'Adds a Service dependency method to the *module*DependencyProvider.'
mode: both
deprecated: 'Use AddDependencyBridgeMethod instead.'
arguments:
    organization:
        inherit: true
        default: Spryker
    module:
        inherit: true
    dependentModule:
        inherit: true
        moduleFilter:
            application: Service
    providerMethod:
        value: 'add{{ dependentModule }}Service'
    template:
        value: Client/Dependency/Service/ClientDependencyServiceDependencyProviderMethod.php.twig
    target:
        value: '{{ organization }}\Client\{{ module }}\{{ module }}DependencyProvider'
preSpryks:
    - AddClientDependencyProvider
postSpryks:
    -
        AddConstant:
            arguments:
                name: 'SERVICE_{{ dependentModule | underscored | upper }}'
                value: 'SERVICE_{{ dependentModule | underscored | upper }}'
                visibility: public
                target: '{{ organization }}\Client\{{ module }}\{{ module }}DependencyProvider'
