spryk: method
description: 'Adds a Service dependency method to the *module*Factory.'
mode: both
deprecated: 'Use AddDependencyBridgeMethod instead.'
arguments:
    organization:
        inherit: true
        default: Spryker
    application:
        value: Client
    module:
        inherit: true
    dependentModule:
        inherit: true
        moduleFilter:
            application: Service
    factoryMethod:
        value: 'get{{ dependentModule }}Service'
    template:
        value: Client/Dependency/Service/ClientDependencyServiceFactoryMethod.php.twig
    target:
        value: '{{ organization }}\Client\{{ module }}\{{ module }}Factory'
preSpryks:
    - AddClientDependencyProvider
    - AddClientFactory
postSpryks:
    -
        AddConstant:
            arguments:
                name: 'SERVICE_{{ dependentModule | underscored | upper }}'
                value: 'SERVICE_{{ dependentModule | underscored | upper }}'
                visibility: public
                target: '{{ organization }}\Client\{{ module }}\{{ module }}DependencyProvider'
