spryk: template
description: "Adds a new *module*BusinessFactory to the Zed application."
mode: both
level: 3
condition: "application === 'Zed' && layer === 'Business'"

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        value: "Zed"

    layer:
        inherit: false
        default: "Business"

    template:
        value: Zed/Business/ZedBusinessFactory.php.twig

    targetFilename:
        value: "{{ module }}BusinessFactory.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Business/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedBusinessFacade
    - AddZedDependencyProvider
    - AddModuleConfig:
          arguments:
              application: "Zed"
