name: AddZedBusinessFactoryDependencyMethod
spryk: method
description: "Adds a dependency method to the *module*BusinessFactory."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    dependencyType: ~
    dependentModule: ~

    template:
        value: Zed/Business/DependencyMethodBusinessFactory.php.twig

    target:
        value: "{{ organization }}\\Zed\\{{ module }}\\Business\\{{ module }}BusinessFactory"

preSpryks:
    - AddZedBusinessFactory

postSpryks:
    - AddZedDependencyFacadeBridgeMethod:
          arguments:
              dependentModule:
                  value: "MessageBroker"
              methods:
                  value:
                      - "sendMessage"
