name: AddZedBusinessFacadeInterface
spryk: template
description: "Adds a new *module*FacadeInterface to the Zed application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        inherit: true
        default: Zed

    template:
        value: Zed/Business/ZedBusinessFacadeInterface.php.twig

    targetFilename:
        value: "{{ module }}FacadeInterface.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Business/"

preSpryks:
    - AddModule
