spryk: template
description: 'Adds a new Business DomainEntity updater to the Zed application.'
mode: both
level: 2
application: Zed
layer: Business
priority: 1
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    className:
        value: '{{ domainEntity }}Updater'
    domainEntity:
        inherit: true
    subDirectory:
        value: '{{ domainEntity }}/Writer'
    template:
        value: Zed/Business/DomainEntity/Writer/DomainEntityUpdater.php.twig
    targetFilename:
        value: '{{ domainEntity }}Updater.php'
    targetPath:
        value: 'src/{{ organization }}/Zed/{{ module }}/Business/'
preSpryks:
    - AddModule
postSpryks:
    -
        AddZedBusinessModelInterfaceMethod:
            arguments:
                className: '{{ domainEntity }}Updater'
                subDirectory: '{{ domainEntity }}/Writer'
                modelMethod: 'update{{ domainEntity }}Collection'
                input: '\Generated\Shared\Transfer\{{ domainEntity }}CollectionRequestTransfer ${{ domainEntity | lcfirst }}CollectionRequestTransfer'
                output: '\Generated\Shared\Transfer\{{ domainEntity }}CollectionResponseTransfer'
    -
        AddZedBusinessFactoryMethod:
            arguments:
                output: '\{{ organization }}\Zed\{{ module }}\Business\{{ domainEntity }}\Writer\{{ domainEntity }}UpdaterInterface'
                dependencyMethods:
                    - getEntityManager
                    - 'create{{ domainEntity }}UpdateValidator'
                    - 'create{{ domainEntity }}IdentifierBuilder'
                    - 'get{{ domainEntity }}PreUpdatePlugins'
                    - 'get{{ domainEntity }}PostUpdatePlugins'
