name: AddZedDomainEntityCreator
spryk: template
description: "Adds a new Business DomainEntity creator to the Zed application."
mode: both
level: 2

application: Zed
layer: Business

priority: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    className:
        value: "{{ domainEntity }}Creator"

    domainEntity:
        inherit: true

    subDirectory:
        value: "{{ domainEntity }}/Writer"

    template:
        value: Zed/Business/DomainEntity/Writer/DomainEntityCreator.php.twig

    targetFilename:
        value: "{{ domainEntity }}Creator.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Business/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedBusinessModelInterfaceMethod:
          arguments:
              className:
                  value: "{{ domainEntity }}Creator"
              subDirectory:
                  value: "{{ domainEntity }}/Writer"
              modelMethod:
                  value: "create{{ domainEntity }}Collection"
              input:
                  value: "\\Generated\\Shared\\Transfer\\{{ domainEntity }}CollectionRequestTransfer ${{ domainEntity | lcfirst }}CollectionRequestTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\{{ domainEntity }}CollectionResponseTransfer"

    - AddZedBusinessFactoryMethod:
          arguments:
              output:
                  value: "\\{{ organization }}\\Zed\\{{ module }}\\Business\\{{ domainEntity }}\\Writer\\{{ domainEntity }}CreatorInterface"
              dependencyMethods:
                  value:
                      - "getEntityManager"
                      - "create{{ domainEntity }}CreateValidator"
                      - "create{{ domainEntity }}IdentifierBuilder"
                      - "get{{ domainEntity }}PreCreatePlugins"
                      - "get{{ domainEntity }}PostCreatePlugins"
