spryk: method
description: 'Adds a Client dependency method to the *module*Factory.'
mode: both
deprecated: 'Use AddDependencyBridgeMethod instead.'
arguments:
    organization:
        inherit: true
        default: Spryker
    application:
        value: Client
    module:
        inherit: true
    dependentModule:
        inherit: true
        moduleFilter:
            application: Client
    factoryMethod:
        value: 'get{{ dependentModule }}Client'
    template:
        value: Client/Dependency/Client/ClientDependencyClientFactoryMethod.php.twig
    target:
        value: '{{ organization }}\Client\{{ module }}\{{ module }}Factory'
preSpryks:
    - AddClientDependencyProvider
    - AddClientFactory
postSpryks:
    -
        AddConstant:
            arguments:
                name: 'CLIENT_{{ dependentModule | underscored | upper }}'
                value: 'CLIENT_{{ dependentModule | underscored | upper }}'
                visibility: public
                target: '{{ organization }}\Client\{{ module }}\{{ module }}DependencyProvider'
