spryk: schemaProperty
description: "Adds a Persistence schema to *module*.schema.xml in the Zed application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    domainEntity:
        inherit: true

    name:
        inherit: true

    propertyName: ~

    propertyType: ~

    required:
        default: false

    autoIncrement:
        default: false

    primaryKey:
        default: false

    size:
        default: false

    defaultValue:
        default: ""

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Persistence/Propel/Schema/spy_{{ module | underscored }}.schema.xml"

preSpryks:
    - AddZedPersistencePropelSchemaTable:
          arguments:
              tableName:
                  value: "spy_{{ domainEntity | underscored }}"
              targetModule:
                  value: "{{ module | underscored }}"
