spryk: wrapper
description: "Adds a Persistence schema to *module*.schema.xml in the Zed application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    domainEntity:
        inherit: true

    propertyName:
        inherit: true

postSpryks:
    - AddZedPersistencePropelSchemaUniqueKey:
        arguments:
            name:
                value: "spy_{{ domainEntity | underscored }}"
            keyName:
                value: "spy_{{ domainEntity | underscored }}-unique-{{ propertyName }}"
            columns:
                value:
                    - "{{ propertyName }}"
