spryk: template
description: "Adds a new *module*Config to the Zed application."
deprecated: "Use AddModule config instead."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Zed/ZedConfig.php.twig

    extends:
        callback: ResolveExtends
        value:
            - "\\Spryker\\Zed\\{{ module }}\\{{ module }}Config"
            - "\\Spryker\\Zed\\Kernel\\AbstractBundleConfig"

    targetFilename:
        value: "{{ module }}Config.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/"

#preSpryks:
#    - AddModule
