spryk: template
description: 'Adds a new Processor model to the Glue application.'
mode: both
application: Glue
priority: 1
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    subDirectory:
        inherit: true
        default: RestResponseBuilder
    resourceType:
        inherit: true
    className:
        inherit: true
        value: '{{ resourceType | dashToCamelCase | singularize }}RestResponseBuilder'
    interfaceName:
        inherit: true
        value: '{{ className }}Interface'
    constructorArguments:
        type: GlueProcessorDependency
        typeOptions:
            - module
            - spryk
        isMultiple: true
        isOptional: true
        value:
            - '\Spryker\Glue\GlueApplication\Rest\JsonApi\RestResourceBuilderInterface $restResourceBuilder'
            - '\{{ organization }}\Glue\{{ module }}\Processor\Mapper\{{ resourceType | dashToCamelCase | singularize }}MapperInterface ${{ resourceType | dashToCamelCase | singularize | lcfirst }}Mapper'
    template:
        value: Glue/Processor/GlueProcessorModel.php.twig
    targetFilename:
        callbackOnly: true
        callback: GlueProcessorModelTargetFilename
    targetPath:
        value: 'src/{{ organization }}/Glue/{{ module }}/Processor/'
AddGlueResourceRestResponseBuilderModel:
    yml: ~
preSpryks:
    - AddModule
postSpryks:
    -
        AddGlueResourceRestResponseBuilderModelInterface:
            arguments:
                className:
                    default: '{{ resourceType | dashToCamelCase | singularize }}RestResponseBuilder'
                interfaceName:
                    default: '{{ resourceType | dashToCamelCase | singularize }}RestResponseBuilderInterface'
    -
        AddGlueResourceMapperInterface:
            arguments:
                className: '{{ resourceType | dashToCamelCase | singularize }}Mapper'
                subDirectory: Mapper
    -
        AddGlueResourceMapper:
            arguments:
                className: '{{ resourceType | dashToCamelCase | singularize }}Mapper'
                subDirectory: Mapper
    -
        AddGlueResourceRestResponseBuilderFactoryMethod:
            arguments:
                dependencyMethods:
                    - getResourceBuilder
                    - 'create{{ resourceType | dashToCamelCase | singularize }}Mapper'
                className: '{{ resourceType | dashToCamelCase | singularize }}RestResponseBuilder'
                subDirectory: RestResponseBuilder
