spryk: structure
description: 'Adds a new Data Import module structure. Property entity must be in camel case.'
priority: 1
mode: both
level: 1
arguments:
    organization:
        inherit: true
        default: Spryker
    application:
        inherit: true
        default: Zed
    module:
        inherit: true
        type: NewModuleType
    entity:
        inherit: true
    targetPath:
        value: ''
    directories:
        skipOnProjectLevel: true
        value:
            - 'src/{{ organization }}/'
preSpryks:
    - AddModule
postSpryks:
    - AddSharedTransferSchema
    -
        AddSharedTransferDefinition:
            arguments:
                name: DataImporterConfiguration
    -
        AddSharedTransferDefinition:
            arguments:
                name: DataImporterReport
    -
        AddModuleConfig:
            arguments:
                extends: \Spryker\Zed\DataImport\DataImportConfig
    -
        AddZedDependencyProvider:
            arguments:
                extends: \Spryker\Zed\DataImport\DataImportDependencyProvider
    - AddDataImportZedBusinessFactoryMethod
    - AddZedBusinessFacade
    -
        AddMethod:
            arguments:
                method: 'get{{ entity }}DataImporterConfiguration'
                input: ''
                output: \Generated\Shared\Transfer\DataImporterConfigurationTransfer
                target: '\{{ organization }}\{{ application }}\{{ module }}\{{ module }}Config'
                withInterface: false
    -
        AddConstant:
            arguments:
                name: 'IMPORT_TYPE_{{ entity | underscored | upper }}'
                value: '{{ entity | dasherize }}'
                visibility: public
                target: '\{{ organization }}\Zed\{{ module }}\{{ module }}Config'
    -
        AddZedBusinessFacadeMethod:
            arguments:
                facadeMethod: 'import{{ entity }}'
                input: '?\Generated\Shared\Transfer\DataImporterConfigurationTransfer $dataImporterConfigurationTransfer = null'
                output: \Generated\Shared\Transfer\DataImporterReportTransfer
                body: 'return $this->getFactory()->get{{ entity }}DataImporter()->import($dataImporterConfigurationTransfer);'
    -
        AddDataImportZedBusinessWriterStepMethod:
            arguments:
                className: '{{ entity }}DataImportWriterStep'
                subDirectory: DataImportStep
                modelMethod: execute
                input: '\Spryker\Zed\DataImport\Business\Model\DataSet\DataSetInterface $dataSet'
                output: void
    - AddZedCommunicationFactory
    - AddDataImportPlugin
    - AddZedPersistenceEntityManager
    - AddZedPersistenceRepository
    - AddZedTestCodeceptionConfiguration
    - AddZedTestSuiteToCodeceptionConfiguration
