spryk: template
description: 'Adds a new Business DomainEntity reader to the Zed application.'
mode: both
level: 2
application: Zed
layer: Business
priority: 1
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    className:
        value: '{{ domainEntity }}Reader'
    domainEntity:
        inherit: true
    subDirectory:
        value: '{{ domainEntity }}/Reader'
    template:
        value: Zed/Business/DomainEntity/Reader/DomainEntityReader.php.twig
    targetFilename:
        value: '{{ domainEntity }}Reader.php'
    targetPath:
        value: 'src/{{ organization }}/Zed/{{ module }}/Business/'
preSpryks:
    - AddModule
postSpryks:
    -
        AddZedBusinessModelInterfaceMethod:
            arguments:
                className: '{{ domainEntity }}Reader'
                subDirectory: '{{ domainEntity }}/Reader'
                modelMethod: 'get{{ domainEntity }}Collection'
                input: '\Generated\Shared\Transfer\{{ domainEntity }}CriteriaTransfer ${{ domainEntity | lcfirst }}CriteriaTransfer'
                output: '\Generated\Shared\Transfer\{{ domainEntity }}CollectionTransfer'
    -
        AddZedBusinessFactoryMethod:
            arguments:
                output: '\{{ organization }}\Zed\{{ module }}\Business\{{ domainEntity }}\Reader\{{ domainEntity }}ReaderInterface'
                dependencyMethods:
                    - getRepository
                    - 'get{{ domainEntity }}ExpanderPlugins'
