spryk: template
description: "Adds a new *module*PersistenceFactory to the Zed application."
mode: both
level: 3
condition: "application === 'Zed' && layer === 'Persistence'"

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        value: Zed

    layer:
        inherit: false
        default: "Persistence"

    template:
        value: Zed/Persistence/ZedPersistenceFactory.php.twig

    targetFilename:
        value: "{{ module }}PersistenceFactory.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
    - AddModule

