name: AddZedPersistenceFactory
spryk: template
description: "Adds a new *module*PersistenceFactory to the Zed application."
mode: both
level: 3
condition: "application === 'Zed' && layer === 'Persistence'"

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        value: Zed

    layer:
        inherit: false
        default: "Persistence"

    extends:
        callback: ResolveExtends
        value:
            - "\\Spryker\\{{ application }}\\{{ module }}\\Persistence\\{{ module }}PersistenceFactory"
            - "\\Spryker\\{{ application }}\\Kernel\\Persistence\\AbstractPersistenceFactory"

    className:
        value: "{{ module }}PersistenceFactory"

    annotations:
        value:
            - "@method \\{{ organization }}\\{{ application }}\\{{ module }}\\{{ module }}Config getConfig()"
            - "@method \\{{ organization }}\\{{ application }}\\{{ module }}\\Persistence\\{{ module }}RepositoryInterface getRepository()"
            - "@method \\{{ organization }}\\{{ application }}\\{{ module }}\\Persistence\\{{ module }}EntityManagerInterface getEntityManager()"

    template:
        value: Common/Class.php.twig

    subDirectory:
        value: "Persistence"

    targetFilename:
        value: "{{ module }}PersistenceFactory.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/"

preSpryks:
    - AddModule

