spryk: template
description: "Adds a new *module*To*dependentModule*ServiceBridge."
mode: core
deprecated: Use AddDependencyBridgeMethod instead.

arguments:
    module:
        inherit: true
        moduleFilter:
            application: Zed

    organization:
        inherit: true
        default: Spryker

    dependentModule:
        inherit: true
        moduleFilter:
            application: Service

    dependentModuleOrganization:
        default: Spryker

    template:
        value: Zed/Dependency/Service/ZedDependencyServiceBridge.php.twig

    targetFilename:
        value: "{{ module }}To{{ dependentModule }}ServiceBridge.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Dependency/Service/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedDependencyServiceInterface
    - AddZedDependencyServiceBusinessFactoryMethod
    - AddZedDependencyServiceDependencyProviderMethod
    - AddZedDependencyServiceDependencyProviderConstant:
        arguments:
            name:
                value: "SERVICE_{{ dependentModule | underscored | upper }}"
            value:
                value: "SERVICE_{{ dependentModule | underscored | upper }}"
            visibility:
                value: "public"
