spryk: wrapper
description: 'Adds transfers for *domainEntity* to be used in common entity manipulation facade.'
mode: both
level: 2
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    application:
        inherit: true
        default: Shared
    domainEntity:
        inherit: true
    targetPath:
        value: 'src/{{ organization }}/Shared/{{ module }}/Transfer/{{ module | underscored }}.transfer.xml'
postSpryks:
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}'
                propertyName: 'id{{ domainEntity | ucfirst }}'
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}'
                propertyName: uuid
                propertyType: string
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}CollectionRequest'
                propertyName: isTransactional
                propertyType: bool
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}CollectionRequest'
                propertyName: '{{ domainEntity | lcfirst | pluralize }}'
                propertyType: '{{ domainEntity | ucfirst }}[]'
                singular: '{{ domainEntity | lcfirst }}'
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}CollectionResponse'
                propertyName: errors
                propertyType: 'Error[]'
                singular: error
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}CollectionResponse'
                propertyName: '{{ domainEntity | lcfirst | pluralize }}'
                propertyType: '{{ domainEntity | ucfirst }}[]'
                singular: '{{ domainEntity | lcfirst }}'
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}CollectionDeleteCriteria'
                propertyName: isTransactional
                propertyType: bool
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}CollectionDeleteCriteria'
                propertyName: '{{ domainEntity | lcfirst }}Ids'
                propertyType: 'int[]'
                singular: 'id{{ domainEntity | ucfirst }}'
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}CollectionDeleteCriteria'
                propertyName: uuids
                propertyType: 'string[]'
                singular: uuid
    -
        AddSharedTransferProperty:
            arguments:
                name: Error
                propertyName: message
                propertyType: string
    -
        AddSharedTransferProperty:
            arguments:
                name: Error
                propertyName: entityIdentifier
                propertyType: string
