name: AddSharedTransferProperty
spryk: transferProperty
description: "Adds a new property to *module*.transfer.xml in the Shared application."
mode: both
level: 2

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    application:
        inherit: true
        default: Shared

    name:
        description: "The name of the Transfer to be build. Can be empty when transfersProperties is used."
        inherit: true
        default: ""

    transfersProperties:
        description: "Used when Multiple transfers needs to be added otherwise empty. Format: TransferA&propertyA:string,propertyB:int:singular;TransferB&propertyA:string,propertyB:int:singular"

    propertyName:
        description: "The name of the property to be added. Can be empty when transfersProperties is used."
        default: ""

    propertyType:
        description: "The type of the property to be added. Can be empty when transfersProperties is used."
        default: ""

    singular:
        default: false

    targetPath:
        value: "src/{{ organization }}/Shared/{{ module }}/Transfer/{{ module | underscored }}.transfer.xml"

preSpryks:
    - AddSharedTransferDefinition

postSpryks:
    - AddDataBuilderProperty
