spryk: wrapper
description: 'Adds transfers for *domainEntity* to be used in common entity fetching facade.'
mode: both
level: 2
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    application:
        inherit: true
        default: Shared
    domainEntity:
        inherit: true
    targetPath:
        value: 'src/{{ organization }}/Shared/{{ module }}/Transfer/{{ module | underscored }}.transfer.xml'
postSpryks:
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}Criteria'
                propertyName: '{{ domainEntity | lcfirst }}Conditions'
                propertyType: '{{ domainEntity | ucfirst }}Conditions'
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}Criteria'
                propertyName: sortCollection
                propertyType: 'Sort[]'
                singular: sort
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}Criteria'
                propertyName: pagination
                propertyType: Pagination
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}Conditions'
                propertyName: '{{ domainEntity | lcfirst }}Ids'
                propertyType: 'int[]'
                singular: '{{ domainEntity | lcfirst }}Id'
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}Conditions'
                propertyName: uuids
                propertyType: 'string[]'
                singular: uuid
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}Collection'
                propertyName: '{{ domainEntity | lcfirst | pluralize }}'
                propertyType: '{{ domainEntity | ucfirst }}[]'
                singular: '{{ domainEntity | lcfirst }}'
    -
        AddSharedTransferProperty:
            arguments:
                name: '{{ domainEntity | ucfirst }}Collection'
                propertyName: pagination
                propertyType: Pagination
    -
        AddSharedTransferProperty:
            arguments:
                name: Sort
                propertyName: field
                propertyType: string
    -
        AddSharedTransferProperty:
            arguments:
                name: Sort
                propertyName: isAscending
                propertyType: bool
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: limit
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: offset
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: page
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: maxPerPage
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: nbResults
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: firstIndex
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: lastIndex
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: firstPage
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: lastPage
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: nextPage
                propertyType: int
    -
        AddSharedTransferProperty:
            arguments:
                name: Pagination
                propertyName: previousPage
                propertyType: int
