spryk: method
description: 'Adds a Service dependency method to the *module*Factory.'
mode: both
arguments:
    organization:
        inherit: true
        default: SprykerShop
    module:
        inherit: true
    dependentModule:
        inherit: true
        moduleFilter:
            application: Service
    factoryMethod:
        value: 'get{{ dependentModule }}Service'
    template:
        value: Yves/Dependency/Service/YvesDependencyServiceFactoryMethod.php.twig
    target:
        value: '{{ organization }}\Yves\{{ module }}\{{ module }}Factory'
preSpryks:
    - AddYvesFactory
postSpryks:
    -
        AddYvesDependencyServiceDependencyProviderConstant:
            arguments:
                name: 'SERVICE_{{ dependentModule | underscored | upper }}'
                value: 'SERVICE_{{ dependentModule | underscored | upper }}'
                visibility: public
