spryk: template
description: 'Adds a new *module*To*dependentModule*ServiceBridge.'
mode: core
arguments:
    organization:
        inherit: true
        default: SprykerShop
    module:
        inherit: true
    dependentModule:
        inherit: true
        moduleFilter:
            application: Service
    dependentModuleOrganization:
        inherit: true
        default: Spryker
    template:
        value: Yves/Dependency/Service/YvesDependencyServiceBridge.php.twig
    targetFilename:
        value: '{{ module }}To{{ dependentModule }}ServiceBridge.php'
    targetPath:
        value: 'src/{{ organization }}/Yves/{{ module }}/Dependency/Service/'
preSpryks:
    - AddModule
postSpryks:
    - AddYvesDependencyServiceInterface
    - AddYvesDependencyServiceFactoryMethod
    - AddYvesDependencyServiceDependencyProviderMethod
    -
        AddYvesDependencyServiceDependencyProviderConstant:
            arguments:
                name: 'SERVICE_{{ dependentModule | underscored | upper }}'
                value: 'SERVICE_{{ dependentModule | underscored | upper }}'
                visibility: public
