spryk: template
description: 'Adds a new Business DomainEntity deleter to the Zed application.'
mode: both
level: 2
application: Zed
layer: Business
priority: 1
arguments:
    module:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    domainEntity: ~
    className:
        value: '{{ domainEntity }}Deleter'
    subDirectory:
        value: '{{ domainEntity }}/Deleter'
    template:
        value: Zed/Business/DomainEntity/Deleter/DomainEntityDeleter.php.twig
    targetFilename:
        value: '{{ domainEntity }}Deleter.php'
    targetPath:
        value: 'src/{{ organization }}/Zed/{{ module }}/Business/'
preSpryks:
    - AddModule
postSpryks:
    -
        AddZedBusinessModelInterfaceMethod:
            arguments:
                className: '{{ domainEntity }}Deleter'
                subDirectory: '{{ domainEntity }}/Deleter'
                modelMethod: 'delete{{ domainEntity }}Collection'
                input: '\Generated\Shared\Transfer\{{ domainEntity }}CollectionDeleteCriteriaTransfer ${{ domainEntity | lcfirst }}CollectionDeleteCriteriaTransfer'
                output: '\Generated\Shared\Transfer\{{ domainEntity }}CollectionResponseTransfer'
    -
        AddZedBusinessFactoryMethod:
            arguments:
                output: '\{{ organization }}\Zed\{{ module }}\Business\{{ domainEntity }}\Deleter\{{ domainEntity }}DeleterInterface'
                dependencyMethods:
                    - getEntityManager
                    - getRepository
