name: "Build spryk.phar"

on:
    push:
#    workflow_run:
#        workflows: [ "CI" ]
#        types:
#            - completed

jobs:
    build:
        name: Build
        runs-on: "ubuntu-latest"
        timeout-minutes: 60

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  php-version: "7.4"

            - name: Composer install
              run: composer install --no-interaction --no-progress

# This should replace the next two steps
            - name: Build caches and compile the PHAR
              run: bin/console spryk:compile

#            - name: Build caches and compile the PHAR
#              run: |
#                  bin/console spryk:build
#                  bin/console cache:clear -e prod
#                  bin/console cache:warmup -e prod
#
#            - name: Compile PHAR
#              working-directory: "compiler/build"
#              run: php box.phar compile --no-parallel

            - uses: actions/upload-artifact@v3
              with:
                  name: phar-file
                  path: tmp/spryk.phar

            - name: Delete PHAR
              run: rm tmp/spryk.phar

    commit:
        name: Commit spryk.phar
        needs: build
        runs-on: "ubuntu-latest"
        timeout-minutes: 60
        steps:
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: "Checkout target repository"
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PAT }}
                  repository: spryker-sdk/spryk
                  path: spryk-target
                  fetch-depth: 0

            - name: Download spryk.phar
              uses: actions/download-artifact@v3
              with:
                  name: phar-file

            - name: Copy phar from source to target
              run: mv spryk.phar spryk-target/spryk.phar

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.PAT }}
                  path: spryk-target
                  branch: ${{steps.extract_branch.outputs.branch}}
                  delete-branch: true
                  title: Automatic spryk.phar update
                  body: Automatic update of the spryk.phar after "${{steps.extract_branch.outputs.branch}}" was merged to master

            - name: Check outputs
              if: ${{ steps.cpr.outputs.pull-request-number }}
              run: |
                  echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
                  echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
